### ISSUE TITLE
NoMethodError: undefined method `primary'

### ISSUE THREAD

**Issue by grimmwerks** [voormedia/rails-erd#142]
Just ran, got this:

```
Loading application environment...
Loading code in search of Active Record models...
Generating Entity-Relationship Diagram for 10 models...
rake aborted!
NoMethodError: undefined method `primary' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x007fe77c83d2e8>
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/domain/attribute.rb:52:in `primary_key?'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/domain/attribute.rb:40:in `content?'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:180:in `block (2 levels) in filtered_attributes'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:180:in `each'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:180:in `none?'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:180:in `block in filtered_attributes'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:177:in `reject'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:177:in `filtered_attributes'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:129:in `block in generate'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:128:in `each'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:128:in `generate'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:119:in `create'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:74:in `create'
/Users/grimm/.rvm/gems/ruby-2.1.0/gems/rails-erd-1.1.0/lib/rails_erd/tasks.rake:41:in `block (2 levels) in <top (required)>'
/Users/grimm/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
/Users/grimm/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => erd => erd:generate
(See full trace by running task with --trace)
```

**Comment by johnhamelink** [comment]
:+1: I'm getting this too.

My db/schema:

https://gist.github.com/johnhamelink/1db00cd2e41ed2db21e6

**Comment by kerrizor** [comment]
Ugh! Thanks for the schema - I'll try to repro this and sort it out...

**Comment by johnhamelink** [comment]
Thanks @kerrizor :smile: If you need anything else to help get this fixed give me a shout!

**Comment by kerrizor** [comment]
@johnhamelink Hmmm.. was this with an older version of erd? 1.4.x is the latest version..

**Comment by johnhamelink** [comment]
@kerrizor yep, it seems to have fixed its self after and update.

**Comment by kerrizor** [comment]
Awesome! Glad to hear it.
