### ISSUE TITLE
No Entities Found in Rails Application Using Local Config File

### ISSUE THREAD

**Issue by jkozlick** [voormedia/rails-erd#180]
The following error message is generated when when running `rake erd --trace` from the root of a rails project when a `.erdconfig` file is located in the Rails root directory. The project is using **Ruby 2.2.1p85**, **Rails 4.2.4** and **rails-erd 1.4.2**.

```
** Invoke erd (first_time)
** Invoke erd:generate (first_time)
** Invoke erd:options (first_time)
** Execute erd:options
** Invoke erd:load_models (first_time)
** Execute erd:load_models
Loading application environment...
** Invoke environment (first_time)
** Execute environment
Loading code in search of Active Record models...
** Execute erd:generate
Generating Entity-Relationship Diagram for 12 models...
rake aborted!
No entities found; create your models first!
/home/user/.rvm/gems/ruby-2.2.1/gems/rails-erd-1.4.2/lib/rails_erd/diagram.rb:159:in `block in filtered_entities'
/home/user/.rvm/gems/ruby-2.2.1/gems/rails-erd-1.4.2/lib/rails_erd/diagram.rb:158:in `tap'
/home/user/.rvm/gems/ruby-2.2.1/gems/rails-erd-1.4.2/lib/rails_erd/diagram.rb:158:in `filtered_entities'
/home/user/.rvm/gems/ruby-2.2.1/gems/rails-erd-1.4.2/lib/rails_erd/diagram.rb:128:in `generate'
/home/user/.rvm/gems/ruby-2.2.1/gems/rails-erd-1.4.2/lib/rails_erd/diagram.rb:119:in `create'
/home/user/.rvm/gems/ruby-2.2.1/gems/rails-erd-1.4.2/lib/rails_erd/diagram.rb:74:in `create'
/home/user/.rvm/gems/ruby-2.2.1/gems/rails-erd-1.4.2/lib/rails_erd/tasks.rake:41:in `block (2 levels) in <top (required)>'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/user/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.2.1/bin/rake:23:in `load'
/home/user/.rvm/gems/ruby-2.2.1/bin/rake:23:in `<main>'
/home/user/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/user/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => erd => erd:generate

```
When no `.erdconfig` file is present, the diagram is rendered without issue.

**Comment by jkozlick** [comment]
Error was generated using the following `.erdconfig` file:

```
attributes:
  - content
  - foreign_key
  - inheritance
disconnected: true
filename: erd
filetype: pdf
indirect: true
inheritance: true
markup: true
notation: simple
orientation: horizontal
polymorphism: false
sort: true
warn: true
title: Application Title
exclude: null
only: null
prepend_primary: false
```

**Comment by hajpoj** [comment]
try removing `only: null`

**Comment by jkozlick** [comment]
Thank you, this fixed it.

Now that you suggested this fix, it makes complete sense, as I was telling rails-erd to create the erd without any models. I guess the source of confusion for me here was that in the Readme, these were described as the default settings. I had started with these in order to create a config file to describe what I needed in my diagram, and was slightly perplexed when it failed.

Thanks again!
