### ISSUE TITLE
Native PostgreSQL / Postgis Datatypes not working

### ISSUE THREAD

**Issue by tilo** [voormedia/rails-erd#181]
Native PostgreSQL data type are not working, e.g. Hash or JSON

```
$ bundle exec erd --debug

Loading application in 'the_app'...
Generating entity-relationship diagram for 10 models...
Failed: NoMethodError: undefined method `to_sym' for {}:Hash
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/lib/rails_erd/diagram.rb:154:in `map'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/lib/rails_erd/diagram.rb:154:in `block in filtered_entities'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/lib/rails_erd/diagram.rb:152:in `reject'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/lib/rails_erd/diagram.rb:152:in `filtered_entities'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/lib/rails_erd/diagram.rb:128:in `generate'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/lib/rails_erd/diagram.rb:119:in `create'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/lib/rails_erd/diagram.rb:74:in `create'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/lib/rails_erd/cli.rb:159:in `create_diagram'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/lib/rails_erd/cli.rb:142:in `start'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/lib/rails_erd/cli.rb:131:in `start'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/gems/rails-erd-1.4.4/bin/erd:4:in `<top (required)>'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/bin/erd:23:in `load'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/bin/erd:23:in `<main>'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from /Users/tilo/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kerrizor** [comment]
I'm unable to reproduce this with hstore or jsonb data types.

![erd pdf 1 page 2016-05-15 10-34-02](https://cloud.githubusercontent.com/assets/257689/15275729/8f27bdf6-1a88-11e6-96e7-83a0e171e437.png)

Are you able to reproduce this problem under rails-erd 1.4.7? If so, can you share the DB schema for the model that is breaking?
