### ISSUE TITLE
NoMethodError: undefined method `collection?'

### ISSUE THREAD

**Issue by avantjustus** [voormedia/rails-erd#291]
Hello, I attempted to run this gem based on the instructions here: https://voormedia.github.io/rails-erd/install.html

I installed the gem using `gem 'rails-erd'` and then ran `bundle install`, which installed version 1.5.2. After that, I ran `rake erd` and received the following output/error:
```
Loading code in search of Active Record models...
[some warnings]
Generating Entity-Relationship Diagram for 515 models...
[warnings ignoring invalid associations/models]
rake aborted!
NoMethodError: undefined method `collection?' for #<PowerEnum::Reflection::EnumerationReflection:0x007ff9ed03e7f8>
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/domain/relationship.rb:183:in `association_maximum'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/domain/relationship.rb:170:in `block in associations_range'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/domain/relationship.rb:170:in `map'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/domain/relationship.rb:170:in `associations_range'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/domain/relationship.rb:85:in `cardinality'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/domain/relationship.rb:120:in `to_many?'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram/graphviz.rb:101:in `block in relationship_style'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram/graphviz.rb:97:in `tap'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram/graphviz.rb:97:in `relationship_style'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram/graphviz.rb:292:in `relationship_options'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram/graphviz.rb:234:in `block in <class:Graphviz>'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:144:in `instance_exec'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:144:in `block in generate'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:143:in `each'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:143:in `generate'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:119:in `create'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/diagram.rb:74:in `create'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rails-erd-1.5.2/lib/rails_erd/tasks.rake:55:in `block (2 levels) in <top (required)>'
/Users/justus/.rvm/gems/ruby-2.3.4/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/justus/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
/Users/justus/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by kerrizor** [comment]
It looks like the association returned by the `power_enum` gem are not fully compatible with the `ActiveRecord` objects they patch and/or replace. Can you share the project you're experiencing this on?

Closing for now.
