### ISSUE TITLE
Generation fails for paper_trail models with custom version classes

### ISSUE THREAD

**Issue by inclooder** [voormedia/rails-erd#303]
Use this snippet to reproduce.
https://github.com/paper-trail-gem/paper_trail#6a-custom-version-classes

backtrace
```
Failed: NoMethodError: undefined method `name' for nil:NilClass
    from /app/rails-erd/lib/rails_erd/domain.rb:102:in `block (2 levels) in relationships_mapping'
    from /app/rails-erd/lib/rails_erd/domain.rb:100:in `each'
    from /app/rails-erd/lib/rails_erd/domain.rb:100:in `block in relationships_mapping'
    from /app/rails-erd/lib/rails_erd/domain.rb:99:in `tap'
    from /app/rails-erd/lib/rails_erd/domain.rb:99:in `relationships_mapping'
    from /app/rails-erd/lib/rails_erd/domain.rb:77:in `relationships_by_entity_name'
    from /app/rails-erd/lib/rails_erd/domain/attribute.rb:80:in `foreign_key?'
    from /app/rails-erd/lib/rails_erd/diagram.rb:207:in `block (2 levels) in filtered_attributes'
    from /app/rails-erd/lib/rails_erd/diagram.rb:207:in `each'
    from /app/rails-erd/lib/rails_erd/diagram.rb:207:in `none?'
    from /app/rails-erd/lib/rails_erd/diagram.rb:207:in `block in filtered_attributes'
    from /app/rails-erd/lib/rails_erd/diagram.rb:204:in `reject'
    from /app/rails-erd/lib/rails_erd/diagram.rb:204:in `filtered_attributes'
    from /app/rails-erd/lib/rails_erd/diagram.rb:136:in `block in generate'
    from /app/rails-erd/lib/rails_erd/diagram.rb:135:in `each'
    from /app/rails-erd/lib/rails_erd/diagram.rb:135:in `generate'
    from /app/rails-erd/lib/rails_erd/diagram.rb:119:in `create'
    from /app/rails-erd/lib/rails_erd/diagram.rb:74:in `create'
    from /app/rails-erd/lib/rails_erd/cli.rb:183:in `create_diagram'
    from /app/rails-erd/lib/rails_erd/cli.rb:157:in `start'
 ```
I have a fix for this, will push it shortly.

**Comment by kerrizor** [comment]
Fixed in #325
