### ISSUE TITLE
Getting Error while generating ERD - No such method constantinize

### ISSUE THREAD

**Issue by rajesh-talreja** [voormedia/rails-erd#332]
I ran the below commands and getting no such method error - 
```
FDLMC2421:freshteam jeshta$ **rake erd filetype=dot**
Loading application environment...
Loading code in search of Active Record models...
rake aborted!
Loading models failed!
Error occurred while loading application: undefined method `constantize' for :"Ats::Job":Symbol (NoMethodError)
    app/models/ats/applicant.rb:3:in `<class:Applicant>'
    app/models/ats/applicant.rb:2:in `<module:Ats>'
    app/models/ats/applicant.rb:1:in `<top (required)>'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/rails-erd-1.6.0/lib/rails_erd/tasks.rake:50:in `rescue in block (2 levels) in <top (required)>'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/rails-erd-1.6.0/lib/rails_erd/tasks.rake:38:in `block (2 levels) in <top (required)>'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/bin/ruby_executable_hooks:24:in `eval'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/bin/ruby_executable_hooks:24:in `<main>'
NoMethodError: undefined method `constantize' for :"Ats::Job":Symbol
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/bundler/gems/acts_as_tenant-e10384f6be6b/lib/acts_as_tenant/model_extensions.rb:126:in `block in acts_as_tenant'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/bundler/gems/acts_as_tenant-e10384f6be6b/lib/acts_as_tenant/model_extensions.rb:124:in `each'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/bundler/gems/acts_as_tenant-e10384f6be6b/lib/acts_as_tenant/model_extensions.rb:124:in `acts_as_tenant'
/Users/jeshta/Documents/workspace/freshteam/app/models/ats/applicant.rb:3:in `<class:Applicant>'
/Users/jeshta/Documents/workspace/freshteam/app/models/ats/applicant.rb:2:in `<module:Ats>'
/Users/jeshta/Documents/workspace/freshteam/app/models/ats/applicant.rb:1:in `<top (required)>'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:477:in `load'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:477:in `block in load_file'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:662:in `new_constants_in'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:476:in `load_file'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:375:in `block in require_or_load'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:37:in `load_interlock'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:358:in `require_or_load'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:336:in `depend_on'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:252:in `require_dependency'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/railties-5.0.2/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/railties-5.0.2/lib/rails/engine.rb:475:in `each'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/railties-5.0.2/lib/rails/engine.rb:475:in `block in eager_load!'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/railties-5.0.2/lib/rails/engine.rb:473:in `each'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/railties-5.0.2/lib/rails/engine.rb:473:in `eager_load!'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/rails-erd-1.6.0/lib/rails_erd/tasks.rake:39:in `block (2 levels) in <top (required)>'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/bin/ruby_executable_hooks:24:in `eval'
/Users/jeshta/.rvm/gems/ruby-2.3.1@freshteam/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => erd => erd:generate => erd:load_models
(See full trace by running task with --trace)
FDLMC2421:freshteam jeshta$ ruby --versiom
ruby: invalid option --versiom  (-h will show valid options) (RuntimeError)
FDLMC2421:freshteam jeshta$ **ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin18]**
FDLMC2421:freshteam jeshta$ **rails --version
Rails 5.0.2**
FDLMC2421:freshteam jeshta$ 


```

**Comment by kerrizor** [comment]
Hmmm interesting. It looks like there's a conflict with `acts_as_tenant` during `Rails.application.eager_load!` for some reason. It looks like the issue is here https://github.com/ErwinM/acts_as_tenant/blob/e10384f6be6ba0a37a53f0d22e2c770c4374d797/lib/acts_as_tenant/model_extensions.rb#L126, and considering that its a problem in a 2.5 year old commit, might want to ping @erwinm on this.
