### ISSUE TITLE
Fails to ignore models and dependencies outside development group

### ISSUE THREAD

**Issue by belgoros** [voormedia/rails-erd#349]
As explained in the [configuration](https://github.com/voormedia/rails-erd#configuration) section, I created a custom `.erdconfig.yml` file in the app root:
```yml
exclude: "MystoreModel,StoreInfo,StorePeriod,StoreSchedule,StoreWelcome"
```
to ignore some models using `activerecord-oracle_enhanced-adapter` gem defined to be used in `staging` and `production` environments only:
```yml
# Gemfile

group :development, :test do
...
  gem 'rails-erd',             '~> 1.5', '>= 1.5.2'
end

group :staging, :production do
  gem 'activerecord-oracle_enhanced-adapter', '~> 5.2.0'
  gem 'ruby-oci8',                            '~> 2.2', '>= 2.2.7'
  gem 'aws-sdk-s3', '~> 1.48', require: false
end
```
By the way, it is not really clear if the name of the custom `.erdconfig` should be `.erdconfig.yml` or just `erdconfig`. None of them worked anyway.

When running `bundle exec erd`, it raised the error:
```
Loading application in 'my-app-name'...
Failed: LoadError: Could not load the 'oracle_enhanced' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile.
```
I also tried to pass the above option from the CLI:
```
rails erd exclude: "MystoreModel,StoreInfo,StorePeriod,StoreSchedule,StoreWelcome"
```
with the same failure:
```
Loading application environment...
Loading code in search of Active Record models...
rails aborted!
Loading models failed!
Error occurred while loading application: Could not load the 'oracle_enhanced' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile. (LoadError)
    app/lib/mystore_migration/mystore_model.rb:5:in `<class:MystoreModel>'
    app/lib/mystore_migration/mystore_model.rb:4:in `<module:MystoreMigration>'
    app/lib/mystore_migration/mystore_model.rb:3:in `<main>'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/rails-erd-1.6.0/lib/rails_erd/tasks.rake:50:in `rescue in block (2 levels) in <main>'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/rails-erd-1.6.0/lib/rails_erd/tasks.rake:38:in `block (2 levels) in <main>'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/command.rb:48:in `invoke'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/Serguei/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'

Caused by:
LoadError: Could not load the 'oracle_enhanced' Active Record adapter. Ensure that the adapter is spelled correctly in config/database.yml and that you've added the necessary adapter gem to your Gemfile.
```

What is wrong with that? Why is ERD trying to load the gems outside the `development` group?

**Comment by belgoros** [comment]
My bad, I figured out. The error came from the following `establish_connection` call in the base oracle-related model:
```ruby
  class MystoreModel < ApplicationRecord
    establish_connection(:mystore) if (Rails.env.staging? or Rails.env.producction?)
  end
```
where `:mystore` connection used `activerecord-oracle_enhanced-adapter`.
Running `bundle exec erd` has generated the diagram excluding the specified models.
