### ISSUE TITLE
module_parent vs parent

### ISSUE THREAD

**Issue by ciembor** [voormedia/rails-erd#358]
Rails version: Rails 6.0.2.1

Error: 

`Failed: ActiveSupport::DeprecationException: DEPRECATION WARNING: 'Module#parent` has been renamed to 'module_parent'. 'parent' is deprecated and will be removed in Rails 6.1. `

Solution: in `lib/rails_erd/domain.rb:52` replace `Rails.application.class.module_parent.name` with `Rails.application.class.parent.name`. But...

Rails version: Rails 5.2.4.3

In this version rails-erd works, but it doesn't with changed code:

`Failed: NoMethodError: undefined method 'module_parent'`

I think rails-erd is very usefull also in old projects, during takeover by new developers. Solution would be to handle both cases, maybe using `respond_to?` or to get this `name` in a different way.

**Comment by ciembor** [comment]
We can use:

```
if Rails::VERSION::MAJOR >= 6
  Rails.application.class.module_parent.name
else
  Rails.application.class.parent.name
end
```

This is the cleanest way to handle this. We can also use partition:

```
Rails.application.class.name.partition('::').first
```

**Comment by gee-forr** [comment]
I can confirm it's not working. Running Rails 6.1 rc1 and I'm getting this when I attempt to generate an ERD:

```
Loading application environment...
Loading code in search of Active Record models...
Generating Entity-Relationship Diagram for 35 models...
rails aborted!
NoMethodError: undefined method `parent' for SomeRandomApp::Application:Class
Did you mean?  present?
/app/bin/rails:4:in `require'
/app/bin/rails:4:in `<top (required)>'
/app/bin/spring:7:in `require'
/app/bin/spring:7:in `block in <top (required)>'
/app/bin/spring:4:in `tap'
/app/bin/spring:4:in `<top (required)>'
/app/config/boot.rb:4:in `load'
/app/config/boot.rb:4:in `<top (required)>'
Tasks: TOP => erd => erd:generate
```

**Comment by gee-forr** [comment]
It looks like there's been a PR that will resolve this #345 from September 2019. It's CI builds are failing though :(

**Comment by smartinez87** [comment]
close in favor of #503

**Comment by homonecloco** [comment]
This seems to be solved by #365

**Comment by kerrizor** [comment]
Hey @ciembor! 👋

This was fixed a while ago! The codebase now uses `respond_to?(:module_parent)` to handle both Rails 5.x and 6.x+:

```ruby
if Rails.application.class.respond_to?(:module_parent)
  Rails.application.class.module_parent.name
else
  Rails.application.class.parent.name
end
```

The fix has been in the gem since v1.7.0. If you're still on an older version, please upgrade! 🙏
