### ISSUE TITLE
rails-red conflicts with discard gem

### ISSUE THREAD

**Issue by alec-c4** [voormedia/rails-erd#374]
Hey!
I have model SalesPerson 

``` ruby
class SalesPerson < ApplicationRecord
  include IdentityCache
  include Discard::Model

  validates :referral_code, uniqueness: true, presence: true
  validates :name, presence: true

  default_scope -> { kept }
end 
```

which is working with [discard](https://github.com/jhawthorn/discard) gem. Every time i try to generate erd file i see following error

```
Running via Spring preloader in process 76935
Loading application environment...
Loading code in search of Active Record models...
rake aborted!
Loading models failed!
Error occurred while loading application: uninitialized constant SalesPerson::Discard (NameError)
    app/models/sales_person.rb:3:in `<class:SalesPerson>'
    app/models/sales_person.rb:1:in `<main>'
<internal:/Users/alec/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/alec/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
-e:1:in `<main>'

Caused by:
NameError: uninitialized constant SalesPerson::Discard
```

How to fix it?

**Comment by mjobin-mdsol** [comment]
are you sure its related to `rails-erd` ? does not appear like so ...

**Comment by kerrizor** [comment]
Hey @alec-c4! 👋

As @mjobin-mdsol mentioned, this doesn't appear to be a rails-erd issue. The error `uninitialized constant SalesPerson::Discard` means the Discard gem isn't being loaded before your model.

This is likely a load order issue in your Rails application. Some things to try:

1. Make sure `discard` is in your Gemfile (not just in a group)
2. Try adding `require 'discard'` at the top of your model file
3. Check if you're using Spring and try `spring stop` then retry

Since this is a gem loading issue in your application rather than a rails-erd bug, I'm closing this. If you believe it's actually a rails-erd issue, please reopen with more details! 🙏
