### ISSUE TITLE
Bug with --only and -only_recursion_depth 

### ISSUE THREAD

**Issue by LucasCarrias** [voormedia/rails-erd#376]
### What:
An exception is raised when you provide a single model name with `--only` and `--only_recursion_depth`

### Step to reproduce:
At the CLI, enter `--only` with just one model name, then provide `--only_recursion_depth` with any valid integer.

Example:
`erd --only ModelName --only_recursion_depth=1`

### Debug:

rails-erd 1.6.1

```
Failed: NoMethodError: undefined method `each' for "ModelName":String
    from /home/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/rails-erd-1.6.1/lib/rails_erd/diagram.rb:129:in `generate'
    from /home/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/rails-erd-1.6.1/lib/rails_erd/diagram.rb:119:in `create'
    from /home/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/rails-erd-1.6.1/lib/rails_erd/diagram.rb:74:in `create'
    from /home/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/rails-erd-1.6.1/lib/rails_erd/cli.rb:193:in `create_diagram'
    from /home/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/rails-erd-1.6.1/lib/rails_erd/cli.rb:167:in `start'
    from /home/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/rails-erd-1.6.1/lib/rails_erd/cli.rb:156:in `start'
    from /home/ruby/2.7.5/lib/ruby/gems/2.7.0/gems/rails-erd-1.6.1/bin/erd:4
```

### Possible fix:

Make sure that `options[:only]` is always an array

https://github.com/voormedia/rails-erd/blob/e41243f6d33303bfc9bdc1cff159bb1986cbee22/lib/rails_erd/diagram.rb#L129-L132

**Comment by kerrizor** [comment]
Hey @lucascarrias! 👋

Thanks for the detailed bug report - your diagnosis was spot on! 🎯

I've just merged #441 which ensures `options[:only]` is always an array before iterating, using the same `[value].flatten` pattern already used elsewhere in the codebase.

The fix is now on master. You can test with:

```ruby
gem 'rails-erd', github: 'voormedia/rails-erd'
```

Thanks again for reporting this! 🙏
