### ISSUE TITLE
rails db:migrate

### ISSUE THREAD

**Issue by ogola5** [voormedia/rails-erd#402]
NameError: uninitialized constant Products
/home/ogola/Practice/crud/config/routes.rb:2:in `block in <main>'
/home/ogola/Practice/crud/config/routes.rb:1:in `<main>'
/home/ogola/Practice/crud/config/environment.rb:5:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)

**Comment by schmijos** [comment]
I would assume that you've got a Rails application in front of you. Can you please check if the file `app/models/product.rb` exists? And it should contain a class called `Product`.

**Comment by jasonkarns** [comment]
I'm betting this can be closed now?

**Comment by kerrizor** [comment]
Thanks you for the comments, Jason. I will take a look.

**Comment by kerrizor** [comment]
Hey @ogola5! 👋

This error is not related to rails-erd - it's a Rails routing/model configuration issue in your application. The error `NameError: uninitialized constant Products` means Rails can't find a `Products` class.

As @schmijos mentioned, you likely need to:
1. Create the model file `app/models/product.rb` (note: singular `Product`, not `Products`)
2. Make sure it contains `class Product < ApplicationRecord`

This is a general Rails issue, not specific to rails-erd. I'd recommend checking out the [Rails Getting Started Guide](https://guides.rubyonrails.org/getting_started.html) for help with model setup.

Closing this as it's not a rails-erd issue. Good luck with your Rails project! 🚀
