### ISSUE TITLE
ERD generation fails in project using gem ActiveType

### ISSUE THREAD

**Issue by mhmaguire** [voormedia/rails-erd#79]
I have a project where I'm using the gem [ActiveType](https://github.com/makandra/active_type). Erd fails when one of my models inherits from ActiveType::Record

Not 100% sure if this is really an issue with rails-erd, as this gem does some weird things to make plain old ruby classes quack like active record models

**excerpt from active type readme**

---

ActiveType::Record[BaseClass] is used to extend a given BaseClass (that itself has to be an ActiveRecord model) with additional functionality, that is not meant to be shared to the rest of the application.

You class will inherit from BaseClass. You can add additional methods, validations, callbacks, as well as use (virtual) attributes like an ActiveType::Object:

class SignUp < ActiveType::Record[User]
  # ...
end

---

**app to reproduce**

here is a test application which reproduces the error. simply setup the application and attempt to run 
`bundle exec rake erd`

https://github.com/mhmaguire/erd_active_type_test

**stack trace** 

```
bundle exec rake erd inheritance=true polymorphism=true attributes=primary_keys,foreign_keys  --trace
** Invoke erd (first_time)
** Invoke erd:generate (first_time)
** Invoke erd:options (first_time)
** Execute erd:options
** Invoke erd:load_models (first_time)
** Execute erd:load_models
Loading application environment...
** Invoke environment (first_time)
** Execute environment
Loading code in search of Active Record models...
** Execute erd:generate
Generating Entity-Relationship Diagram for 5 models...
Warning: Ignoring invalid model ActiveType::Object (table objects does not exist)
rake aborted!
ArgumentError: comparison of RailsERD::Domain::Entity with RailsERD::Domain::Entity failed
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rails-erd-1.1.0/lib/rails_erd/domain/entity.rb:8:in `sort'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rails-erd-1.1.0/lib/rails_erd/domain/entity.rb:8:in `from_models'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rails-erd-1.1.0/lib/rails_erd/domain.rb:57:in `entities'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:152:in `filtered_entities'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:128:in `generate'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:119:in `create'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rails-erd-1.1.0/lib/rails_erd/diagram.rb:74:in `create'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rails-erd-1.1.0/lib/rails_erd/tasks.rake:41:in `block (2 levels) in <top (required)>'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/mhmaguir/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:199:in `each'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/mhmaguir/.rvm/rubies/ruby-1.9.3-p429/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/bin/rake:23:in `load'
/home/mhmaguir/.rvm/gems/ruby-1.9.3-p429/bin/rake:23:in `<main>'
Tasks: TOP => erd => erd:generate
```

**Comment by kerrizor** [comment]
I've not had time to look into this, unfortunately, so if someone comes along and wants it..

**Comment by Nitrodist** [comment]
@kerrizor what would you prefer the output to be? To just generate it at all -- as if the ActiveType object didn't exist? Or do you want it to exist in the ERD?

**Comment by kerrizor** [comment]
If I'm understanding, `ActiveType` objects aren't backed by DB records, and thus don't really represent Domain Entity models as we (rails-erd) think of them. Now, they *may* be super important to users, but I don't think we want to show them in the graph; doing so would be adding specific, one-off support for a particular gem, and could lead to confusion for some end users ("Hey, wait, this is a view model, not a DB model, why is it in my ERD?!") 

We should remove them from consideration by rails-erd, so that this sort of error doesn't occur. If the ActiveType people want to add support for this, I'd welcome a PR, obviously :)

Should be easy to add [somewhere in here](https://github.com/voormedia/rails-erd/blob/master/lib/rails_erd/domain/entity.rb#L7) something like

```
model_list = (concrete_from_models(domain, models) + abstract_from_models(domain, models)).sort

model_list.select{ |model| model.respond_to? :table_name && model.table_name.exist? }.sort
```
