### ISSUE TITLE
Saving diagram failed.

### ISSUE THREAD

**Issue by mdi** [voormedia/rails-erd#8]
On a Mac. Using (installed via Homebrew):
    graphviz 2.26.3
    pango 1.28.3
    cairo 1.8.10

Running `rake erd --trace`, I get the following error. Happens with `filetype=dot` too:

```
** Invoke erd (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute erd
rake aborted!
Saving diagram failed. Verify that Graphviz is installed or select filetype=dot.
/Library/Ruby/Gems/1.8/gems/rails-erd-0.4.3/lib/rails_erd/diagram/graphviz.rb:173
/Library/Ruby/Gems/1.8/gems/rails-erd-0.4.3/lib/rails_erd/diagram.rb:142:in `instance_eval'
/Library/Ruby/Gems/1.8/gems/rails-erd-0.4.3/lib/rails_erd/diagram.rb:142:in `save'
/Library/Ruby/Gems/1.8/gems/rails-erd-0.4.3/lib/rails_erd/diagram.rb:120:in `create'
/Library/Ruby/Gems/1.8/gems/rails-erd-0.4.3/lib/rails_erd/diagram.rb:74:in `create'
./tasks/misc.rake:18
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19
```

**Comment by rubyconsumer** [comment]
I had the error "Verify that Graphviz is installed and in your path, or use filetype=dot." show up and couldn't figure out what was going on.

rails-erd worked on another project but not a new one. Once I rolled back to a previous version a new error showed up, "routesplines, cannot find NORMAL edge", and that led me down to a solution as show in #70.  After implementing a fix, I was able to update back to the newest version and every works as expected.

**Summary**: if not of the above solutions work, check out the solution shown in Issue #70.
